<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="entity\" />
    <Folder Include="controller\" />
    <Folder Include="jwt\" />
    <Folder Include="dto\" />
    <Folder Include="config\" />
    <Folder Include="websocket\" />
    <Folder Include="sercurity\" />
    <Folder Include="service\" />
    <Folder Include="repository\" />

			  
  </ItemGroup>

</Project>
